apiVersion: qlik.com/v1
kind: Qliksense
metadata:
  name: qliksense-default
  labels:
    version: v0.0.1
spec:
  profile: docker-desktop
  configs:
    qliksense:
      - name: acceptEULA
        value: "yes"
      - name: acceptEULA
        value: "yes"
  manifestsRoot: /Users/mqb/.qliksense/contexts/qliksense-default/qlik-k8s/v0.0.1/manifests
  storageClassName: mokul
  namespace: namespace
