apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: qliksense-operator
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs: 
  - create
  - delete
  - get
  - list
  - watch

