apiVersion: apps/v1
kind: Deployment
metadata:
  name: qliksense-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: qliksense-operator
  template:
    metadata:
      labels:
        name: qliksense-operator
    spec:
      serviceAccountName: qliksense-operator
      containers:
        - name: qliksense-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
            - qliksense-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "qliksense-operator"
