apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: qliksense-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - deployments
  - replicasets
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - deployments/finalizers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - qlik.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  - ingresses/status
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - qixmanager.qlik.com
  resources:
  - engines
  - engines/finalizers
  verbs:
  - '*'
- apiGroups:
  - qixengine.qlik.com
  resources:
  - engines
  - engines/finalizers
  - engines/status
  - enginevariants
  - enginevariants/status
  - enginevariants/finalizers
  - enginetemplates
  - enginetemplates/finalizers
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'