// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CombinedSpec) DeepCopyInto(out *CombinedSpec) {
	*out = *in
	if in.CRSpec != nil {
		in, out := &in.CRSpec, &out.CRSpec
		*out = (*in).DeepCopy()
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsMeta)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CombinedSpec.
func (in *CombinedSpec) DeepCopy() *CombinedSpec {
	if in == nil {
		return nil
	}
	out := new(CombinedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsMeta) DeepCopyInto(out *GitOpsMeta) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsMeta.
func (in *GitOpsMeta) DeepCopy() *GitOpsMeta {
	if in == nil {
		return nil
	}
	out := new(GitOpsMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Qliksense) DeepCopyInto(out *Qliksense) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CombinedSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Qliksense.
func (in *Qliksense) DeepCopy() *Qliksense {
	if in == nil {
		return nil
	}
	out := new(Qliksense)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Qliksense) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QliksenseList) DeepCopyInto(out *QliksenseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Qliksense, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QliksenseList.
func (in *QliksenseList) DeepCopy() *QliksenseList {
	if in == nil {
		return nil
	}
	out := new(QliksenseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QliksenseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QliksenseSpec) DeepCopyInto(out *QliksenseSpec) {
	*out = *in
	in.CRSpec.DeepCopyInto(&out.CRSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QliksenseSpec.
func (in *QliksenseSpec) DeepCopy() *QliksenseSpec {
	if in == nil {
		return nil
	}
	out := new(QliksenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QliksenseStatus) DeepCopyInto(out *QliksenseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QliksenseStatus.
func (in *QliksenseStatus) DeepCopy() *QliksenseStatus {
	if in == nil {
		return nil
	}
	out := new(QliksenseStatus)
	in.DeepCopyInto(out)
	return out
}
